2025-03-20 19:34:01 - web - DEBUG - This is a debug message.
2025-03-20 19:34:01 - web - INFO - This is an info message.
2025-03-20 19:34:01 - web - WARNING - This is a warning message.
2025-03-20 19:34:01 - web - ERROR - This is an error message.
2025-03-20 19:34:01 - web - CRITICAL - This is a critical message.
2025-03-20 20:16:08 - web - DEBUG - This is a debug message.
2025-03-20 20:16:08 - web - INFO - This is an info message.
2025-03-20 20:16:08 - web - WARNING - This is a warning message.
2025-03-20 20:16:08 - web - ERROR - This is an error message.
2025-03-20 20:16:08 - web - CRITICAL - This is a critical message.
2025-03-21 03:17:03 - web - INFO - This is an info message.
2025-03-21 03:18:24 - web - INFO - This is an info message.
2025-03-21 03:24:55 - web - INFO - ip地址是：127.0.0.1
2025-03-21 03:24:55 - web - INFO - This is an info message.
2025-03-21 03:35:03 - web - INFO - ip地址是：127.0.0.1
2025-03-21 03:37:49 - web - INFO - ip地址是：127.0.0.1
2025-03-21 03:46:15 - web - INFO - ip地址是：127.0.0.1
2025-03-21 03:46:17 - web - INFO - ip地址是：127.0.0.1
2025-03-21 03:53:24 - web - INFO - ip地址是：127.0.0.1
2025-03-21 04:48:21 - web - INFO - ip地址是：127.0.0.1
2025-03-21 06:03:19 - web - ERROR - Failed to save login log: 'type'
Traceback (most recent call last):
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\web\views\account.py", line 90, in login
    login_device_type = device_info['device']['type']  # 使用设备类型
KeyError: 'type'
2025-03-21 07:28:51 - web - ERROR - Failed to save login log: (1048, "Column 'login_city' cannot be null")
Traceback (most recent call last):
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1048, "Column 'login_city' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\web\views\account.py", line 76, in login
    models.LoginLog.objects.create(
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\base.py", line 763, in save_base
    updated = self._save_table(
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\base.py", line 906, in _do_insert
    return manager._insert(
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\sql\compiler.py", line 1410, in execute_sql
    cursor.execute(sql, params)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1048, "Column 'login_city' cannot be null")
2025-03-21 07:29:52 - web - ERROR - Failed to save login log: (1048, "Column 'login_city' cannot be null")
Traceback (most recent call last):
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1048, "Column 'login_city' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\web\views\account.py", line 76, in login
    models.LoginLog.objects.create(
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\base.py", line 763, in save_base
    updated = self._save_table(
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\base.py", line 906, in _do_insert
    return manager._insert(
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\sql\compiler.py", line 1410, in execute_sql
    cursor.execute(sql, params)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1048, "Column 'login_city' cannot be null")
2025-03-21 07:32:39 - web - ERROR - Failed to save login log: (1048, "Column 'login_city' cannot be null")
Traceback (most recent call last):
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1048, "Column 'login_city' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\web\views\account.py", line 76, in login
    models.LoginLog.objects.create(
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\base.py", line 763, in save_base
    updated = self._save_table(
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\base.py", line 906, in _do_insert
    return manager._insert(
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\sql\compiler.py", line 1410, in execute_sql
    cursor.execute(sql, params)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1048, "Column 'login_city' cannot be null")
2025-03-21 07:33:13 - web - ERROR - Failed to save login log: (1048, "Column 'login_city' cannot be null")
Traceback (most recent call last):
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1048, "Column 'login_city' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\web\views\account.py", line 76, in login
    models.LoginLog.objects.create(
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\base.py", line 763, in save_base
    updated = self._save_table(
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\base.py", line 906, in _do_insert
    return manager._insert(
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\sql\compiler.py", line 1410, in execute_sql
    cursor.execute(sql, params)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1048, "Column 'login_city' cannot be null")
2025-03-21 07:34:59 - web - ERROR - Failed to save login log: (1048, "Column 'login_city' cannot be null")
Traceback (most recent call last):
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1048, "Column 'login_city' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\web\views\account.py", line 76, in login
    models.LoginLog.objects.create(
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\base.py", line 763, in save_base
    updated = self._save_table(
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\base.py", line 906, in _do_insert
    return manager._insert(
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\sql\compiler.py", line 1410, in execute_sql
    cursor.execute(sql, params)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1048, "Column 'login_city' cannot be null")
2025-03-21 07:35:31 - web - ERROR - Failed to save login log: (1048, "Column 'login_city' cannot be null")
Traceback (most recent call last):
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1048, "Column 'login_city' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\web\views\account.py", line 76, in login
    models.LoginLog.objects.create(
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\base.py", line 763, in save_base
    updated = self._save_table(
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\base.py", line 906, in _do_insert
    return manager._insert(
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\models\sql\compiler.py", line 1410, in execute_sql
    cursor.execute(sql, params)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Python_Project\WuPeiQi_Project\Django项目实战&源码分析班\NB_Platform\venvs\lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1048, "Column 'login_city' cannot be null")
2025-03-21 14:17:30 - web - DEBUG - This is a debug message.
2025-03-21 14:17:35 - web - DEBUG - This is a debug message.
2025-03-21 14:17:35 - web - INFO - This is an info message.
2025-03-21 14:17:35 - web - WARNING - This is a warning message.
2025-03-21 14:17:35 - web - ERROR - This is an error message.
2025-03-21 14:17:35 - web - CRITICAL - This is a critical message.
